import { Timestamp } from '@angular/fire/firestore';
import { Lead } from '../models/lead.model';
import { emptyTouchpoints } from '../services/lead.service';

/**
 * Sample data for local development. Auckland studio — NZ names & mobile numbers.
 * Spread across all four sources and every status, including two trials mid-touchpoint,
 * a Lost lead, and a few Converted ones.
 *
 * Returns documents ready to write straight to Firestore (Timestamps already built).
 * `locationId` is injected by the seed routine so it always matches the active tenant.
 */

const day = 86_400_000;
const ago = (days: number) => Timestamp.fromMillis(Date.now() - days * day);

type SeedLead = Omit<Lead, 'id' | 'locationId'>;

export function buildSeedLeads(): SeedLead[] {
  const tp = emptyTouchpoints;

  return [
    // ---------- NEW CLIENT ----------
    {
      source: 'new',
      name: 'Aroha Williams',
      phone: '021 555 0142',
      email: 'aroha.w@example.co.nz',
      serviceUsed: 'Reformer Pilates',
      notes: 'First class on a casual pass. Loved it.',
      status: 'New',
      contactMethod: 'text',
      createdAt: ago(0.4),
      enteredBy: 'Priya',
      contactedAt: null, contactedBy: null, lastContactAt: null,
      respondedAt: null, convertedAt: null, conversionOutcome: null, lostAt: null,
    },
    {
      source: 'new',
      name: 'Mereana Hayes',
      phone: '027 555 0188',
      email: 'mereana.hayes@example.co.nz',
      serviceUsed: 'Infrared Sauna',
      notes: 'Came in with a friend.',
      status: 'Contacted',
      contactMethod: 'text',
      createdAt: ago(2),
      enteredBy: 'Sam',
      contactedAt: ago(1), contactedBy: 'Sam', lastContactAt: ago(1),
      respondedAt: null, convertedAt: null, conversionOutcome: null, lostAt: null,
    },
    {
      source: 'new',
      name: 'Sophie Walker',
      phone: '022 555 0173',
      email: 'sophie.walker@example.co.nz',
      serviceUsed: 'Group Fitness',
      notes: 'Asked about class timetable.',
      status: 'Converted',
      contactMethod: 'text',
      createdAt: ago(9),
      enteredBy: 'Priya',
      contactedAt: ago(8), contactedBy: 'Priya', lastContactAt: ago(6),
      respondedAt: ago(7), convertedAt: ago(6),
      conversionOutcome: 'Returned / re-booked — back for a second class',
      lostAt: null,
    },

    // ---------- 7-DAY TRIAL ----------
    {
      source: 'trial',
      name: 'Tane Wikaira',
      phone: '021 555 0210',
      email: 'tane.wikaira@example.co.nz',
      serviceUsed: 'Group Fitness',
      notes: null,
      status: 'New',
      contactMethod: 'text',
      createdAt: ago(0.8),
      enteredBy: 'Manaaki',
      contactedAt: null, contactedBy: null, lastContactAt: null,
      respondedAt: null, convertedAt: null, conversionOutcome: null, lostAt: null,
      trialStage: 'Day 1', trialDay: 1,
      experienceNotes: 'Signed up at the desk.',
      touchpoints: tp(),
    },
    {
      // Mid-touchpoint: first service contact done, mid-trial check next.
      source: 'trial',
      name: 'Olivia Chen',
      phone: '027 555 0234',
      email: 'olivia.chen@example.co.nz',
      serviceUsed: 'Reformer Pilates',
      notes: null,
      status: 'Contacted',
      contactMethod: 'text',
      createdAt: ago(3),
      enteredBy: 'Priya',
      contactedAt: ago(3), contactedBy: 'Priya', lastContactAt: ago(2),
      respondedAt: null, convertedAt: null, conversionOutcome: null, lostAt: null,
      trialStage: 'Day 3', trialDay: 3,
      experienceNotes: 'Enjoying it, a bit sore.',
      touchpoints: {
        firstServiceContact: { done: true, at: ago(3), by: 'Priya' },
        midTrialCheck: { done: false, at: null, by: null },
        finalTrialCall: { done: false, at: null, by: null },
      },
    },
    {
      // Mid-touchpoint: first + mid done, final trial call outstanding.
      source: 'trial',
      name: 'Hemi Ngata',
      phone: '021 555 0259',
      email: 'hemi.ngata@example.co.nz',
      serviceUsed: 'Infrared Sauna',
      notes: null,
      status: 'Responded',
      contactMethod: 'text',
      createdAt: ago(5),
      enteredBy: 'Sam',
      contactedAt: ago(5), contactedBy: 'Sam', lastContactAt: ago(2),
      respondedAt: ago(3), convertedAt: null, conversionOutcome: null, lostAt: null,
      trialStage: 'Day 5', trialDay: 5,
      experienceNotes: 'Keen on the sauna + classes combo.',
      touchpoints: {
        firstServiceContact: { done: true, at: ago(5), by: 'Sam' },
        midTrialCheck: { done: true, at: ago(2), by: 'Sam' },
        finalTrialCall: { done: false, at: null, by: null },
      },
    },
    {
      source: 'trial',
      name: 'Charlotte Reti',
      phone: '022 555 0277',
      email: 'charlotte.reti@example.co.nz',
      serviceUsed: 'Group Fitness',
      notes: null,
      status: 'Converted',
      contactMethod: 'text',
      createdAt: ago(12),
      enteredBy: 'Manaaki',
      contactedAt: ago(12), contactedBy: 'Manaaki', lastContactAt: ago(6),
      respondedAt: ago(9), convertedAt: ago(6),
      conversionOutcome: 'Bought a membership — 12-month',
      lostAt: null,
      trialStage: 'Completed', trialDay: 7,
      experienceNotes: 'Loved the community.',
      touchpoints: {
        firstServiceContact: { done: true, at: ago(12), by: 'Manaaki' },
        midTrialCheck: { done: true, at: ago(9), by: 'Manaaki' },
        finalTrialCall: { done: true, at: ago(6), by: 'Manaaki' },
      },
    },

    // ---------- QUIZ LEAD (called, not texted) ----------
    {
      source: 'quiz',
      name: 'Ngaire Solomon',
      phone: '027 555 0301',
      email: 'ngaire.solomon@example.co.nz',
      serviceUsed: null,
      notes: 'Quiz result: stress / recovery focus. Suggested sauna intro.',
      status: 'New',
      contactMethod: 'call',
      createdAt: ago(0.6),
      enteredBy: 'Sam',
      contactedAt: null, contactedBy: null, lastContactAt: null,
      respondedAt: null, convertedAt: null, conversionOutcome: null, lostAt: null,
    },
    {
      source: 'quiz',
      name: 'James Fonoti',
      phone: '021 555 0318',
      email: 'james.fonoti@example.co.nz',
      serviceUsed: null,
      notes: 'Quiz: strength goals. Left voicemail.',
      status: 'Contacted',
      contactMethod: 'call',
      createdAt: ago(2.5),
      enteredBy: 'Priya',
      contactedAt: ago(1.5), contactedBy: 'Priya', lastContactAt: ago(1.5),
      respondedAt: null, convertedAt: null, conversionOutcome: null, lostAt: null,
    },
    {
      source: 'quiz',
      name: 'Ruby Thompson',
      phone: '022 555 0334',
      email: 'ruby.thompson@example.co.nz',
      serviceUsed: null,
      notes: 'Quiz: flexibility. Called back, keen to come in.',
      status: 'Responded',
      contactMethod: 'call',
      createdAt: ago(4),
      enteredBy: 'Manaaki',
      contactedAt: ago(3), contactedBy: 'Manaaki', lastContactAt: ago(1),
      respondedAt: ago(1), convertedAt: null, conversionOutcome: null, lostAt: null,
    },
    {
      source: 'quiz',
      name: 'Manaia Brown',
      phone: '027 555 0349',
      email: null,
      serviceUsed: null,
      notes: 'Quiz lead. Phone disconnected, no other contact.',
      status: 'Lost',
      contactMethod: 'call',
      createdAt: ago(15),
      enteredBy: 'Sam',
      contactedAt: ago(14), contactedBy: 'Sam', lastContactAt: ago(11),
      respondedAt: null, convertedAt: null, conversionOutcome: null, lostAt: ago(8),
    },

    // ---------- PROMO ----------
    {
      source: 'promo',
      name: 'Wiremu Katene',
      phone: '021 555 0360',
      email: 'wiremu.katene@example.co.nz',
      serviceUsed: 'Infrared Sauna',
      notes: 'Bought the floats campaign. Follow up to upsell a pack.',
      status: 'New',
      contactMethod: 'text',
      createdAt: ago(1.2),
      enteredBy: 'Priya',
      contactedAt: null, contactedBy: null, lastContactAt: null,
      respondedAt: null, convertedAt: null, conversionOutcome: null, lostAt: null,
      promoName: '3-Week Floats', purchaseDate: ago(4),
    },
    {
      source: 'promo',
      name: 'Anika Sharma',
      phone: '022 555 0377',
      email: 'anika.sharma@example.co.nz',
      serviceUsed: 'Infrared Sauna',
      notes: 'Summer pass purchaser.',
      status: 'Contacted',
      contactMethod: 'text',
      createdAt: ago(6),
      enteredBy: 'Sam',
      contactedAt: ago(5), contactedBy: 'Sam', lastContactAt: ago(5),
      respondedAt: null, convertedAt: null, conversionOutcome: null, lostAt: null,
      promoName: 'Summer Sauna Pass', purchaseDate: ago(9),
    },
    {
      source: 'promo',
      name: "Daniel O'Connor",
      phone: '027 555 0392',
      email: 'daniel.oconnor@example.co.nz',
      serviceUsed: 'Reformer Pilates',
      notes: 'Promo buyer, upsold after the campaign.',
      status: 'Converted',
      contactMethod: 'text',
      createdAt: ago(20),
      enteredBy: 'Manaaki',
      contactedAt: ago(18), contactedBy: 'Manaaki', lastContactAt: ago(14),
      respondedAt: ago(16), convertedAt: ago(14),
      conversionOutcome: 'Bought a 10-class pack',
      lostAt: null,
      promoName: 'New Year Reset', purchaseDate: ago(24),
    },
  ];
}
