import { Timestamp } from '@angular/fire/firestore';
import { Lead } from '../models/lead.model';
import { emptyTouchpoints } from '../services/lead.service';

/**
 * Sample data for local development. O Studio Remuera — NZ names & mobile numbers.
 * Spread across all five sources and every status, including trials mid-touchpoint,
 * a Lost lead per source, and a few Converted ones. 25 leads so the paginated table
 * spills onto a second page.
 *
 * Returns documents ready to write straight to Firestore (Timestamps already built).
 * `organizationId` is injected by the seed routine so it always matches the active tenant.
 */

const day = 86_400_000;
const ago = (days: number) => Timestamp.fromMillis(Date.now() - days * day);

type SeedLead = Omit<Lead, 'id' | 'organizationId'>;

export function buildSeedLeads(): SeedLead[] {
  const tp = emptyTouchpoints;

  return [
    // ---------- NEW CLIENT (generic New → Contacted → Responded → Converted/Lost) ----------
    {
      source: 'new',
      name: 'Ihaka Morrison',
      phone: '021 555 0102',
      email: 'ihaka.morrison@example.co.nz',
      serviceUsed: 'Reformer Pilates',
      notes: 'First class on a casual pass. Keen to come back.',
      status: 'New',
      contactMethod: 'text',
      createdAt: ago(0.3),      contactedAt: null, lastContactAt: null,
      respondedAt: null, convertedAt: null, conversionOutcome: null, lostAt: null,
    },
    {
      source: 'new',
      name: 'Amelia Blackwood',
      phone: '027 555 0110',
      email: 'amelia.blackwood@example.co.nz',
      serviceUsed: 'Group Fitness',
      notes: 'Walk-in, tried a class with a friend.',
      status: 'Contacted',
      contactMethod: 'text',
      createdAt: ago(3),      contactedAt: ago(1.5), lastContactAt: ago(1.5),
      respondedAt: null, convertedAt: null, conversionOutcome: null, lostAt: null,
    },
    {
      source: 'new',
      name: 'Rawiri Tuhoe',
      phone: '022 555 0118',
      email: 'rawiri.tuhoe@example.co.nz',
      serviceUsed: 'Infrared Sauna',
      notes: 'Asked about the class timetable, texted back keen.',
      status: 'Responded',
      contactMethod: 'text',
      createdAt: ago(6),      contactedAt: ago(5), lastContactAt: ago(2),
      respondedAt: ago(2), convertedAt: null, conversionOutcome: null, lostAt: null,
      // Entered a few days late — the backdated business date the range filter keys off.
      leadDate: ago(9),
    },
    {
      source: 'new',
      name: 'Priya Naidu',
      phone: '021 555 0125',
      email: 'priya.naidu@example.co.nz',
      serviceUsed: 'Group Fitness',
      notes: 'Came in for a second class, signed up.',
      status: 'Converted',
      contactMethod: 'text',
      createdAt: ago(11),      contactedAt: ago(10), lastContactAt: ago(5),
      respondedAt: ago(8), convertedAt: ago(5),
      conversionOutcome: 'Returned / re-booked — back for a second class',
      lostAt: null,
    },
    {
      source: 'new',
      name: 'Jackson Reid',
      phone: '027 555 0131',
      email: 'jackson.reid@example.co.nz',
      serviceUsed: 'Recovery Studio',
      notes: 'One casual visit, no reply to follow-ups.',
      status: 'Lost',
      contactMethod: 'text',
      createdAt: ago(16),      contactedAt: ago(14), lastContactAt: ago(9),
      respondedAt: null, convertedAt: null, conversionOutcome: null, lostAt: ago(9),
    },

    // ---------- 7-DAY TRIAL (three-touchpoint model, not the generic pipeline) ----------
    {
      source: 'trial',
      name: 'Maia Fisher',
      phone: '021 555 0140',
      email: 'maia.fisher@example.co.nz',
      serviceUsed: 'Group Fitness',
      notes: null,
      status: 'New',
      contactMethod: 'text',
      createdAt: ago(0.7),      contactedAt: null, lastContactAt: null,
      respondedAt: null, convertedAt: null, conversionOutcome: null, lostAt: null,
      // Day 1 today — first-visit follow-up due.
      trialStartDate: ago(0.7), trialEndDate: ago(-6.3),
      experienceNotes: 'Signed up at the desk.',
      touchpoints: tp(),
    },
    {
      // Mid-touchpoint: first service contact done, mid-trial check next.
      source: 'trial',
      name: 'Sam Iona',
      phone: '027 555 0147',
      email: 'sam.iona@example.co.nz',
      serviceUsed: 'Reformer Pilates',
      notes: null,
      status: 'Contacted',
      contactMethod: 'text',
      createdAt: ago(3),      contactedAt: ago(3), lastContactAt: ago(2),
      respondedAt: null, convertedAt: null, conversionOutcome: null, lostAt: null,
      // Day 4 — mid-trial check due.
      trialStartDate: ago(3), trialEndDate: ago(-4),
      experienceNotes: 'Enjoying the reformer, a bit sore.',
      touchpoints: {
        firstServiceContact: { done: true, at: ago(3) },
        midTrialCheck: { done: false, at: null },
        finalTrialCall: { done: false, at: null },
      },
    },
    {
      // Mid-touchpoint: first + mid done, final trial call outstanding.
      source: 'trial',
      name: 'Keira Watene',
      phone: '022 555 0153',
      email: 'keira.watene@example.co.nz',
      serviceUsed: 'Infrared Sauna',
      notes: null,
      status: 'Responded',
      contactMethod: 'text',
      createdAt: ago(5),      contactedAt: ago(5), lastContactAt: ago(2),
      respondedAt: ago(3), convertedAt: null, conversionOutcome: null, lostAt: null,
      // Day 6 — between the mid-trial (Day 4) and final-call (Day 7) due days: not queued.
      trialStartDate: ago(5), trialEndDate: ago(-2),
      experienceNotes: 'Keen on the sauna + classes combo.',
      touchpoints: {
        firstServiceContact: { done: true, at: ago(5) },
        midTrialCheck: { done: true, at: ago(3) },
        finalTrialCall: { done: false, at: null },
      },
    },
    {
      source: 'trial',
      name: 'Tobias Lam',
      phone: '021 555 0161',
      email: 'tobias.lam@example.co.nz',
      serviceUsed: 'Group Fitness',
      notes: null,
      status: 'Converted',
      contactMethod: 'text',
      createdAt: ago(13),      contactedAt: ago(13), lastContactAt: ago(6),
      respondedAt: ago(9), convertedAt: ago(6),
      conversionOutcome: 'Bought a membership — 12-month',
      lostAt: null,
      trialStartDate: ago(13), trialEndDate: ago(6),
      experienceNotes: 'Loved the community, all three check-ins done.',
      touchpoints: {
        firstServiceContact: { done: true, at: ago(13) },
        midTrialCheck: { done: true, at: ago(9) },
        finalTrialCall: { done: true, at: ago(6) },
      },
    },
    {
      // Lost mid-trial: first contact happened, then went quiet.
      source: 'trial',
      name: 'Ngaio Patterson',
      phone: '027 555 0168',
      email: 'ngaio.patterson@example.co.nz',
      serviceUsed: 'Recovery Studio',
      notes: null,
      status: 'Lost',
      contactMethod: 'text',
      createdAt: ago(8),      contactedAt: ago(8), lastContactAt: ago(4),
      respondedAt: null, convertedAt: null, conversionOutcome: null, lostAt: ago(4),
      // Legacy doc shape: free-text stage, NO trialStartDate — exercises the createdAt
      // fallback and must render/queue without crashing.
      trialStage: 'Day 4', trialDay: 4,
      experienceNotes: 'Came once, stopped replying after the first check-in.',
      touchpoints: {
        firstServiceContact: { done: true, at: ago(8) },
        midTrialCheck: { done: false, at: null },
        finalTrialCall: { done: false, at: null },
      },
    },

    // ---------- QUIZ LEAD (called, not texted) ----------
    {
      source: 'quiz',
      name: 'Awhina Cole',
      phone: '021 555 0175',
      email: 'awhina.cole@example.co.nz',
      serviceUsed: null,
      notes: 'Quiz result: stress / recovery focus. Suggested sauna intro.',
      status: 'New',
      contactMethod: 'call',
      createdAt: ago(0.5),      contactedAt: null, lastContactAt: null,
      respondedAt: null, convertedAt: null, conversionOutcome: null, lostAt: null,
    },
    {
      source: 'quiz',
      name: 'Marcus Vaeau',
      phone: '027 555 0182',
      email: 'marcus.vaeau@example.co.nz',
      serviceUsed: null,
      notes: 'Quiz: strength goals. Left a voicemail.',
      status: 'Contacted',
      contactMethod: 'call',
      createdAt: ago(2.5),      contactedAt: ago(1.5), lastContactAt: ago(1.5),
      respondedAt: null, convertedAt: null, conversionOutcome: null, lostAt: null,
    },
    {
      source: 'quiz',
      name: 'Holly Sinclair',
      phone: '022 555 0188',
      email: 'holly.sinclair@example.co.nz',
      serviceUsed: null,
      notes: 'Quiz: flexibility. Called back, keen to come in.',
      status: 'Responded',
      contactMethod: 'call',
      createdAt: ago(4),      contactedAt: ago(3), lastContactAt: ago(1),
      respondedAt: ago(1), convertedAt: null, conversionOutcome: null, lostAt: null,
    },
    {
      source: 'quiz',
      name: 'Rangi Thomson',
      phone: '021 555 0195',
      email: 'rangi.thomson@example.co.nz',
      serviceUsed: null,
      notes: 'Quiz: recovery focus. Booked an intro session on the call.',
      status: 'Converted',
      contactMethod: 'call',
      createdAt: ago(10),      contactedAt: ago(9), lastContactAt: ago(4),
      respondedAt: ago(7), convertedAt: ago(4),
      conversionOutcome: 'Booked a visit / came in',
      lostAt: null,
    },
    {
      source: 'quiz',
      name: 'Devon Ellis',
      phone: '027 555 0201',
      email: null,
      serviceUsed: null,
      notes: 'Quiz lead. Phone disconnected, no other contact.',
      status: 'Lost',
      contactMethod: 'call',
      createdAt: ago(15),      contactedAt: ago(14), lastContactAt: ago(10),
      respondedAt: null, convertedAt: null, conversionOutcome: null, lostAt: ago(8),
    },

    // ---------- PROMO (generic pipeline, text contact) ----------
    {
      source: 'promo',
      name: 'Whetu Ranginui',
      phone: '021 555 0208',
      email: 'whetu.ranginui@example.co.nz',
      serviceUsed: 'Infrared Sauna',
      notes: 'Bought the floats campaign. Follow up to upsell a pack.',
      status: 'New',
      contactMethod: 'text',
      createdAt: ago(1.1),      contactedAt: null, lastContactAt: null,
      respondedAt: null, convertedAt: null, conversionOutcome: null, lostAt: null,
      promoName: '3-Week Floats', purchaseDate: ago(4),
    },
    {
      source: 'promo',
      name: 'Bianca Costa',
      phone: '027 555 0214',
      email: 'bianca.costa@example.co.nz',
      serviceUsed: 'Infrared Sauna',
      notes: 'Summer pass purchaser.',
      status: 'Contacted',
      contactMethod: 'text',
      createdAt: ago(6),      contactedAt: ago(5), lastContactAt: ago(5),
      respondedAt: null, convertedAt: null, conversionOutcome: null, lostAt: null,
      promoName: 'Summer Sauna Pass', purchaseDate: ago(9),
    },
    {
      source: 'promo',
      name: 'Kauri Nikora',
      phone: '022 555 0221',
      email: 'kauri.nikora@example.co.nz',
      serviceUsed: 'Reformer Pilates',
      notes: 'Bring-a-friend buyer, replied keen to book in.',
      status: 'Responded',
      contactMethod: 'text',
      createdAt: ago(8),      contactedAt: ago(7), lastContactAt: ago(3),
      respondedAt: ago(3), convertedAt: null, conversionOutcome: null, lostAt: null,
      promoName: 'Bring-a-Friend', purchaseDate: ago(11),
    },
    {
      source: 'promo',
      name: 'Lena Petrova',
      phone: '021 555 0228',
      email: 'lena.petrova@example.co.nz',
      serviceUsed: 'Reformer Pilates',
      notes: 'Promo buyer, upsold after the campaign.',
      status: 'Converted',
      contactMethod: 'text',
      createdAt: ago(19),      contactedAt: ago(17), lastContactAt: ago(13),
      respondedAt: ago(15), convertedAt: ago(13),
      conversionOutcome: 'Bought a 10-class pack',
      lostAt: null,
      promoName: 'New Year Reset', purchaseDate: ago(23),
    },
    {
      source: 'promo',
      name: 'Cody Marsh',
      phone: '027 555 0234',
      email: 'cody.marsh@example.co.nz',
      serviceUsed: 'Group Fitness',
      notes: 'Winter promo buyer, never took up a class. No reply.',
      status: 'Lost',
      contactMethod: 'text',
      createdAt: ago(21),      contactedAt: ago(19), lastContactAt: ago(14),
      respondedAt: null, convertedAt: null, conversionOutcome: null, lostAt: ago(12),
      promoName: 'Winter Warm-Up', purchaseDate: ago(25),
    },

    // ---------- $99 DEALS (generic pipeline, text contact) ----------
    {
      source: 'deal99',
      name: 'Piata Herewini',
      phone: '021 555 0241',
      email: 'piata.herewini@example.co.nz',
      serviceUsed: null,
      notes: 'Grabbed the $99 intro deal online. Follow up to upgrade to a pack.',
      status: 'New',
      contactMethod: 'text',
      createdAt: ago(0.9),      contactedAt: null, lastContactAt: null,
      respondedAt: null, convertedAt: null, conversionOutcome: null, lostAt: null,
      dealName: '$99 Intro Pack', dealPurchaseDate: ago(3),
    },
    {
      source: 'deal99',
      name: 'Oscar Dunn',
      phone: '027 555 0247',
      email: 'oscar.dunn@example.co.nz',
      serviceUsed: null,
      notes: '$99 deal buyer. Texted about membership options.',
      status: 'Contacted',
      contactMethod: 'text',
      createdAt: ago(5),      contactedAt: ago(4), lastContactAt: ago(4),
      respondedAt: null, convertedAt: null, conversionOutcome: null, lostAt: null,
      dealName: '$99 5-Class Deal', dealPurchaseDate: ago(8),
    },
    {
      source: 'deal99',
      name: 'Talia Faleolo',
      phone: '022 555 0254',
      email: 'talia.faleolo@example.co.nz',
      serviceUsed: null,
      notes: '$99 starter buyer, replied asking about pricing.',
      status: 'Responded',
      contactMethod: 'text',
      createdAt: ago(7),      contactedAt: ago(6), lastContactAt: ago(2),
      respondedAt: ago(2), convertedAt: null, conversionOutcome: null, lostAt: null,
      dealName: '$99 Starter Month', dealPurchaseDate: ago(10),
    },
    {
      source: 'deal99',
      name: 'Reuben Clarke',
      phone: '021 555 0261',
      email: 'reuben.clarke@example.co.nz',
      serviceUsed: null,
      notes: 'Upgraded off the $99 deal after a couple of classes.',
      status: 'Converted',
      contactMethod: 'text',
      createdAt: ago(17),      contactedAt: ago(15), lastContactAt: ago(11),
      respondedAt: ago(13), convertedAt: ago(11),
      conversionOutcome: 'Bought a 10-class pack',
      lostAt: null,
      dealName: '$99 Reformer Intro', dealPurchaseDate: ago(21),
    },
    {
      source: 'deal99',
      name: 'Frankie Nolan',
      phone: '027 555 0268',
      email: null,
      serviceUsed: null,
      notes: '$99 deal buyer. Came once, then unreachable.',
      status: 'Lost',
      contactMethod: 'text',
      createdAt: ago(14),      contactedAt: ago(12), lastContactAt: ago(8),
      respondedAt: null, convertedAt: null, conversionOutcome: null, lostAt: ago(6),
      dealName: '$99 Intro Pack', dealPurchaseDate: ago(18),
    },
  ];
}
